# -*- coding: utf-8 -*-
"""ai image

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CrUtS73Ywop3c91Q7y3PsVWqID_3LMM-
"""

# ============================================================
# FORCE COMPATIBLE ENVIRONMENT FOR DEOLDIFY
# ============================================================

!rm -rf DeOldify
!pip uninstall -y torch torchvision fastai -q

# Install OLDER compatible PyTorch (VERY IMPORTANT)
!pip install torch==2.3.0 torchvision==0.18.0 --index-url https://download.pytorch.org/whl/cu118 -q
!pip install fastai==1.0.61 -q
!pip install ffmpeg-python yt-dlp -q

import torch
import functools

# 🔥 Allow old model loading (This line is causing an AttributeError with torch 2.3.0 and is being removed.)
# torch.serialization.add_safe_globals([functools.partial])

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/jantic/DeOldify.git
# %cd DeOldify

!mkdir models
!wget -q https://data.deepai.org/deoldify/ColorizeArtistic_gen.pth \
      -O models/ColorizeArtistic_gen.pth

from deoldify.visualize import *
from deoldify import device
from deoldify.device_id import DeviceId

print("CUDA Available:", torch.cuda.is_available())

if torch.cuda.is_available():
    device.set(device=DeviceId.GPU0)
else:
    device.set(device=DeviceId.CPU)

colorizer = get_image_colorizer(artistic=True)

print("✅ MODEL LOADED SUCCESSFULLY!")

from google.colab import files
from PIL import Image

print("Upload Black & White Image")
uploaded = files.upload()

img_path = list(uploaded.keys())[0]

img = Image.open(img_path).convert("RGB")
input_path = "input.jpg"
img.save(input_path)

print("✅ Image Uploaded Successfully!")

result = colorizer.get_transformed_image(
    path="input.jpg",
    render_factor=45,   # 40 natural, 45 vibrant, 50 strong
    post_process=True
)

result.save("colorized_output.jpg")

print("✅ Saved as colorized_output.jpg")

colorizer.plot_transformed_image(
    path="input.jpg",
    render_factor=45,
    post_process=True,
    watermarked=False,
    compare=True
)